name: GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd java/AutomationTools-Series/github-actions-demo
        mvn clean test
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: report
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit
    - name: Microsoft Teams (Generic)
  # You may pin to the exact commit or the version.
  # uses: aliencube/microsoft-teams-actions@dd5e839bd9f0a79a162d8b6a79065ff525be44b9
      uses: aliencube/microsoft-teams-actions@v0.8.0
       with:
    # Incoming webhook URI to Microsoft Teams
     webhook_uri:https://avaya365.webhook.office.com/webhookb2/1d3af523-1440-45e0-91fe-9739da9f2c55@04a2636c-326d-48ff-93f8-709875bd3aa9/IncomingWebhook/2e537045718e4f9b89fc2a7dc6e0079d/904a03ad-48e3-4462-af62-712501ecb046
    # Message title
    title: # optional, default is 
    # Message summary
    summary: # optional, default is 
    # Message text
    text: # optional, default is 
    # Message theme color
    theme_color: # optional, default is 
    # JSON array for message sections
    sections: # optional, default is 
    # JSON array for message actions
    actions: # optional, default is 
        
